---
# tasks file for neutron DB Setup

- name: DB sync for neutron.
  shell: |
    neutron-db-manage --config-file {{ neutron_config_location }} \
         --config-file {{ neutron_ml2_config_location }} upgrade head
  become: yes
  become_user: "{{ neutron_system_user_name }}"
  ignore_errors: True
  run_once: True
  notify: restart nova api
